Corrige faute frappe
Karocyt/solidity-fr pull request #5
Opened 2021-05-18 19:03 UTC by LudoPL

Corrige une faute de frappe dans un commentaire.

2022-01-10 13:35 UTC, donaldtrumpyyy reviewed
Simple et efficace 👍

2022-02-22 23:39 UTC, Fifie38 requested changes
Faute de frappe dans la correction (voir commentaire) : C'est "autorisent" qu'il faut écrire pas "authorisent"

2022-02-22 23:39 UTC, Fifie38 commented on docs/introduction-to-smart-contracts.rst
> +        // Les Events authorisent les clients légers à réagir
C'est "autorisent" pas "authorisent"

2022-02-23 04:28 UTC, Karocyt commented on docs/introduction-to-smart-contracts.rst
> +        // Les Events authorisent les clients légers à réagir
La crème de la crème qu'on vous dit !

2022-02-23 04:30 UTC, closed without merging